sudo: required

services:
    - docker
    
before_install:
    - docker build -t tomasoares/docker-react-ci -f Dockerfile.dev .

script:
    - docker run tomasoares/docker-react-ci npm run test -- --coverage
    