sudo: required

services:
    - docker
    
before_install:
    - docker build -t tomasoares/docker-react-ci -f Dockerfile.dev .

script:
    - docker run tomasoares/docker-react-ci npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-ci"
    env: "DockerReactCi-env"
    bucket_name: "elasticbeanstalk-us-east-2-267699482760"
    bucket_path: "docker-react-ci"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"